<?php

use ArielMejiaDev\LaravelAdobePdf\Support\Source;
use ArielMejiaDev\LaravelAdobePdf\Tests\TestCase;
use Illuminate\Support\Facades\Http;

uses(TestCase::class)->in(__DIR__);

/**
 * Fake the full Adobe request/response flow:
 * token -> create asset -> upload -> submit -> poll -> download.
 *
 * @param  array<string, mixed>  $status  Overrides for the poll status body.
 */
function fakeAdobeFlow(array $status = []): void
{
    Http::fake([
        '*/token' => Http::response(['access_token' => 'test-token', 'expires_in' => 3600]),
        '*/assets' => Http::response(['uploadUri' => 'https://blob.test/upload/1', 'assetID' => 'urn:aaid:asset:1']),
        '*/upload/*' => Http::response('', 200),
        '*/operation/*' => Http::response('', 201, ['Location' => 'https://pdf-services.adobe.io/status/job-1']),
        '*/status/*' => Http::response(array_merge([
            'status' => 'done',
            'asset' => ['downloadUri' => 'https://blob.test/download/1', 'assetID' => 'urn:aaid:out:1'],
        ], $status)),
        '*/download/*' => Http::response('%PDF-1.7 generated bytes'),
    ]);
}

/**
 * A source built from raw in-memory bytes, so tests never touch the filesystem.
 */
function sourceFixture(string $filename = 'input.pdf', string $contents = '%PDF-1.7 source'): Source
{
    return Source::contents($contents, $filename);
}
