<?php

use ArielMejiaDev\LaravelAdobePdf\Enums\ProcessStatus;
use ArielMejiaDev\LaravelAdobePdf\Facades\LaravelAdobePdf;
use ArielMejiaDev\LaravelAdobePdf\Jobs\ProcessAdobePdfOperation;
use ArielMejiaDev\LaravelAdobePdf\Models\AdobePdfProcess;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Queue;
use Illuminate\Support\Facades\Storage;

it('runs an operation synchronously end to end and stores the result', function () {
    Storage::fake('local');
    fakeAdobeFlow();

    $process = LaravelAdobePdf::extract(sourceFixture('invoice.pdf'))
        ->tables()
        ->text()
        ->dispatchSync();

    expect($process->status)->toBe(ProcessStatus::Completed)
        ->and($process->asset_ids)->toBe(['urn:aaid:asset:1'])
        ->and($process->output_path)->toEndWith('output.zip');

    Storage::disk('local')->assertExists($process->output_path);
    expect($process->output())->toBe('%PDF-1.7 generated bytes');

    Http::assertSent(fn ($request) => str_ends_with($request->url(), '/operation/extractpdf')
        && $request['assetID'] === 'urn:aaid:asset:1'
        && $request['elementsToExtract'] === ['tables', 'text']);
});

it('queues a job and leaves the process pending when dispatched', function () {
    Storage::fake('local');
    fakeAdobeFlow();
    Queue::fake();

    $process = LaravelAdobePdf::create(sourceFixture('doc.docx'))
        ->onQueue('pdfs')
        ->dispatch();

    expect($process->status)->toBe(ProcessStatus::Pending);

    Queue::assertPushed(ProcessAdobePdfOperation::class, fn ($job) => $job->processId === $process->id
        && $job->queue === 'pdfs');
});

it('resolves an html-to-pdf url without uploading any asset', function () {
    Storage::fake('local');
    fakeAdobeFlow();

    $process = LaravelAdobePdf::html('https://example.com/page')->dispatchSync();

    expect($process->status)->toBe(ProcessStatus::Completed)
        ->and($process->asset_ids)->toBe([]);

    // No asset registration call should have happened for a remote URL.
    Http::assertNotSent(fn ($request) => str_ends_with($request->url(), '/assets'));

    Http::assertSent(fn ($request) => str_ends_with($request->url(), '/operation/htmltopdf')
        && $request['inputUrl'] === 'https://example.com/page');
});

it('marks the process failed when adobe reports a failed status', function () {
    Storage::fake('local');
    fakeAdobeFlow(['status' => 'failed', 'error' => ['code' => 'BAD_PDF', 'message' => 'Corrupt file'], 'asset' => null]);

    $process = LaravelAdobePdf::compress(sourceFixture())->dispatchSync();

    expect($process->status)->toBe(ProcessStatus::Failed)
        ->and($process->error['message'])->toContain('Corrupt file');
});

it('times out after the configured number of polls', function () {
    Storage::fake('local');
    config()->set('adobe-pdf.polling.max_attempts', 2);
    fakeAdobeFlow(['status' => 'in progress', 'asset' => null]);

    $process = LaravelAdobePdf::compress(sourceFixture())->dispatchSync();

    expect($process->status)->toBe(ProcessStatus::Failed)
        ->and($process->error['code'])->toBe('TIMEOUT')
        ->and($process->poll_attempts)->toBe(2);
});

it('records a rate limit error on the process when running synchronously', function () {
    Storage::fake('local');
    Http::fake([
        '*/token' => Http::response(['access_token' => 't', 'expires_in' => 3600]),
        '*/assets' => Http::response(['uploadUri' => 'https://blob.test/upload/1', 'assetID' => 'urn:1']),
        '*/upload/*' => Http::response('', 200),
        '*/operation/*' => Http::response(['error' => ['code' => 'TOO_MANY_REQUESTS', 'message' => 'Slow down']], 429),
    ]);

    $process = LaravelAdobePdf::compress(sourceFixture())->dispatchSync();

    expect($process->status)->toBe(ProcessStatus::Failed)
        ->and($process->error['code'])->toBe('TOO_MANY_REQUESTS');
});

it('finds a tracked process by uuid through the facade', function () {
    $process = AdobePdfProcess::factory()->completed()->create();

    expect(LaravelAdobePdf::process($process->uuid)->is($process))->toBeTrue();
});
